-- Java LSP via nvim-jdtls.
--
-- Plain lspconfig can talk to jdtls, but jdtls's genuinely useful features live
-- behind non-standard LSP extensions that only nvim-jdtls knows how to call:
-- organize imports, generate getters/setters/constructors/toString/equals,
-- extract method/variable/constant, and running a single test.
--
-- mason-lspconfig is told NOT to auto-enable jdtls (see plugin/lsp.lua), because
-- this file starts it instead -- otherwise two servers attach to every buffer.

local ok, jdtls = pcall(require, "jdtls")
if not ok then
	return
end

local mason = vim.fn.stdpath("data") .. "/mason/packages/jdtls"
local launcher = mason .. "/bin/jdtls"
if vim.fn.executable(launcher) == 0 then
	vim.notify("nvim-jdtls: jdtls not installed (:MasonInstall jdtls)", vim.log.levels.WARN)
	return
end

-- One workspace per project. Sharing a workspace across projects makes jdtls
-- resolve symbols against the wrong codebase.
local root = vim.fs.root(0, {
	"gradlew", "mvnw", "pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle", ".git",
})
if not root then
	return
end
local workspace = vim.fn.stdpath("cache") .. "/jdtls/" .. vim.fn.fnamemodify(root, ":p:h:t")

-- Debug adapter + test runner, if the Mason packages are present. Without these
-- bundles jdtls has no test-running or debug support at all.
local bundles = {}
vim.list_extend(bundles, vim.fn.glob(
	vim.fn.stdpath("data") .. "/mason/packages/java-debug-adapter/extension/server/com.microsoft.java.debug.plugin-*.jar",
	true, true))
vim.list_extend(bundles, vim.fn.glob(
	vim.fn.stdpath("data") .. "/mason/packages/java-test/extension/server/*.jar", true, true))

-- Spring/Lombok projects need the Lombok javaagent or jdtls cannot see anything
-- generated by @Data, @Getter, @Builder etc. Mason ships the jar.
local lombok = mason .. "/lombok.jar"

local cmd = { launcher, "-data", workspace }
if vim.fn.filereadable(lombok) == 1 then
	table.insert(cmd, "--jvm-arg=-javaagent:" .. lombok)
end

-- Only advertise runtimes that actually exist on this machine.
local runtimes = {}
for name, path in pairs({
	["JavaSE-11"] = vim.env.HOME .. "/Library/Java/JavaVirtualMachines/corretto-11.0.24/Contents/Home",
	["JavaSE-17"] = vim.env.HOME .. "/Library/Java/JavaVirtualMachines/corretto-17.0.13/Contents/Home",
	["JavaSE-21"] = vim.env.HOME .. "/Library/Java/JavaVirtualMachines/corretto-21.0.6/Contents/Home",
}) do
	if vim.fn.isdirectory(path) == 1 then
		table.insert(runtimes, { name = name, path = path })
	end
end

jdtls.start_or_attach({
	cmd = cmd,
	root_dir = root,
	capabilities = require("cmp_nvim_lsp").default_capabilities(),

	init_options = {
		bundles = bundles,
		extendedClientCapabilities = vim.tbl_deep_extend("force",
			jdtls.extendedClientCapabilities or {},
			{ resolveAdditionalTextEditsSupport = true }),
	},

	settings = {
		java = {
			format = { enabled = true },
			saveActions = { organizeImports = true },
			signatureHelp = { enabled = true },
			-- lets you read decompiled bytecode when jumping into a dependency
			contentProvider = { preferred = "fernflower" },
			references = { includeDecompiledSources = true },
			implementationsCodeLens = { enabled = true },
			referencesCodeLens = { enabled = true },
			eclipse = { downloadSources = true },
			maven = { downloadSources = true },
			configuration = { runtimes = runtimes },
			inlayHints = { parameterNames = { enabled = "all" } },
			completion = {
				favoriteStaticMembers = {
					"java.util.Objects.requireNonNull",
					"java.util.Objects.requireNonNullElse",
					"java.util.stream.Collectors.*",
					"org.junit.jupiter.api.Assertions.*",
					"org.mockito.Mockito.*",
					"org.assertj.core.api.Assertions.assertThat",
				},
				importOrder = { "java", "javax", "com", "org" },
			},
			sources = {
				-- never collapse imports into `import java.util.*`
				organizeImports = { starThreshold = 9999, staticStarThreshold = 9999 },
			},
			codeGeneration = {
				toString = {
					template = "${object.className}{${member.name()}=${member.value}, ${otherMembers}}",
				},
				hashCodeEquals = { useJava7Objects = true },
				useBlocks = true,
			},
		},
	},
})

----------------------------------------------------------------------
-- Buffer-local keymaps
----------------------------------------------------------------------
-- Namespaced under <leader>J because most single-letter leader keys are taken,
-- and a colliding prefix would add a timeout delay to the existing mapping.
local function map(mode, lhs, rhs, desc)
	vim.keymap.set(mode, lhs, rhs, { buffer = 0, silent = true, desc = "Java: " .. desc })
end

map("n", "<leader>Jo", jdtls.organize_imports, "organize imports")
map("n", "<leader>Jv", jdtls.extract_variable, "extract variable")
map("v", "<leader>Jv", function() jdtls.extract_variable(true) end, "extract variable")
map("n", "<leader>Jc", jdtls.extract_constant, "extract constant")
map("v", "<leader>Jc", function() jdtls.extract_constant(true) end, "extract constant")
map("v", "<leader>Jm", function() jdtls.extract_method(true) end, "extract method")

-- Test running goes through nvim-dap; only map it if dap is actually installed.
if pcall(require, "dap") then
	map("n", "<leader>Jt", jdtls.test_nearest_method, "test nearest method")
	map("n", "<leader>JT", jdtls.test_class, "test class")
end
